classdef misc_prof_convergence_plots
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    
    properties(Constant=true)
        wrf_dc3_dir = '/Volumes/share2/USERS/LaughnerJ/WRF/DC3/iccg_eq_2-fr_factor_1-mol_flash_500_newprof-fixedBC/';
    end
    
    methods(Static = true)
        function [C, coords] = make_wrf_cov_mat(clon, clat, vert_only)
            % make a covariance matrix centered on a given lat/lon that is
            % 31-by-31 in the lon/lat dimensions. 
            if ~exist('vert_only', 'var')
                vert_only = false;
            end
            
            cut_radius = 15;
            me = misc_prof_convergence_plots;
            F = dir(fullfile(me.wrf_dc3_dir, 'wrfout_subset_*_18-00-00'));
            dnums = date_from_wrf_filenames(F);
            xx = dnums >= datenum('2012-05-18');
            F = F(xx); % remove the first five days for spinup
            
            [no2, lon, lat] = read_wrf_vars(me.wrf_dc3_dir, F, {'no2', 'XLONG', 'XLAT'});
            lon = lon(:,:,1);
            lat = lat(:,:,1);
            
            [~, xx] = min(abs(lon(:) - clon) + abs(lat(:) - clat));
            [x,y] = ind2sub(size(lon), xx);
            no2 = no2((x-cut_radius):(x+cut_radius), (y-cut_radius):(y+cut_radius), :, :);
            lon = repmat(lon((x-cut_radius):(x+cut_radius), (y-cut_radius):(y+cut_radius)), 1, 1, size(no2,3));
            lat = repmat(lat((x-cut_radius):(x+cut_radius), (y-cut_radius):(y+cut_radius)), 1, 1, size(no2,3));
            lev = repmat(permute(1:size(no2,3), [1 3 2]),2*cut_radius+1, 2*cut_radius+1);
            
            sz = size(no2);
            if ~vert_only
                no2 = reshape(no2, prod(sz(1:3)), [])';
            else
                no2 = permute(no2, [3 1 2 4]);
                no2 = reshape(no2, sz(3), [])';
            end
            
            C = corr(no2);
            coords = [lon(:), lat(:), lev(:)];
        end
        
        function cov_map(C, coords, clon, clat, level)
            % Plots the covariance (or correlation) map for a specific
            % level of the covariance/correlation matrix C (generated by
            % make_wrf_cov_mat)
            E = JLLErrors;
            % Find the level, assume that the subdomain chosen is square so
            % we can reshape it.
            xx = coords(:, 3) == level;
            C = C(xx,xx);
            coords = coords(xx,:);
            
            m = sqrt(size(coords,1));
            if mod(m,1) ~= 0
                E.callError('domain_assumption', 'Domain was not square');
            end
            
            lon = reshape(coords(:,1),m,m);
            lat = reshape(coords(:,2),m,m);
            
            [~,mm] = min(abs(lon(:) - clon) + abs(lat(:) - clat));
            cv = reshape(C(mm,:), m, m);
            
            figure; 
            pcolor(lon,lat,cv);
            colorbar;
            colormap jet
            line(clon, clat, 'marker', 'x', 'linewidth', 4, 'linestyle', 'none', 'markersize', 18, 'color', 'w');
        end
    end
    
end

